/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.clientserver;

import java.awt.Color;
import java.io.BufferedInputStream;
import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.net.Socket;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.regex.Pattern;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.swing.JFileChooser;
import javax.swing.SwingUtilities;

/**
 *
 * @author btwyu
 */
public class chat extends javax.swing.JFrame {
    private Socket socket;
    private DataOutputStream dos;
    private DataInputStream dis;
    private String username;
    private String currentRecipient = "ALL"; // Общий чат по умолчанию
    private final Map<String, List<String>> chatHistory = new HashMap<>(); //мапа для истории чата
    private final Map<Integer, File> clickableFiles = new HashMap<>(); //мапа для отслеживания строки

    /**
     * Creates new form chat
     */
  public chat(Socket socket, DataOutputStream dos, DataInputStream dis, String username){
        this.socket = socket;
        this.dos = dos;
        this.dis = dis;
        this.username = username;

        initComponents();
        setTitle("Чат | Вы: «" + username + "»"); 
        setResizable(false);
        setupUserListSelection(); // обработка выбора получателя
        startListening();
    }

    private void setupUserListSelection() {
        jUsers1.addListSelectionListener(e -> {
            if (!e.getValueIsAdjusting()) {
                String selected = jUsers1.getSelectedValue();
                if (selected != null) {
                    currentRecipient = selected.equalsIgnoreCase("Общий чат") ? "ALL" : selected;
                    // ------ динамический заголовок окна ------
                    if ("ALL".equals(currentRecipient)) {
                        setTitle(username + " | Общий чат"); 
                    } else {
                        setTitle(username + " | личный чат с «" + currentRecipient + "»"); 
                    }

                    // Очистим окно чата сразу
                    SwingUtilities.invokeLater(() -> jChat.setText("Загрузка истории...\n"));

                    // Запрашиваем историю у сервера
                    try {
                        dos.writeUTF("GET_HISTORY " + currentRecipient);
                        dos.flush();
                    } catch (IOException ex) {
                        ex.printStackTrace();
                    }
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jMessage = new javax.swing.JTextArea();
        jScrollPane1 = new javax.swing.JScrollPane();
        jChat = new javax.swing.JTextArea();
        jUserList = new javax.swing.JScrollPane();
        jUsers1 = new javax.swing.JList<>();
        jSend = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jFile = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(856, 503));
        setMinimumSize(new java.awt.Dimension(856, 503));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jMessage.setBackground(new java.awt.Color(102, 102, 102));
        jMessage.setColumns(20);
        jMessage.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMessage.setForeground(new java.awt.Color(255, 255, 255));
        jMessage.setRows(5);
        jScrollPane2.setViewportView(jMessage);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 530, 470, 50));

        jChat.setEditable(false);
        jChat.setBackground(new java.awt.Color(153, 153, 153));
        jChat.setColumns(20);
        jChat.setFont(jChat.getFont().deriveFont(jChat.getFont().getSize()+6f));
        jChat.setForeground(new java.awt.Color(255, 255, 255));
        jChat.setLineWrap(true);
        jChat.setRows(5);
        jChat.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jChatMouseMoved(evt);
            }
        });
        jChat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jChatMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jChat);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 13, 590, 510));

        jUsers1.setBackground(new java.awt.Color(102, 102, 102));
        jUsers1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jUsers1.setForeground(new java.awt.Color(255, 255, 255));
        jUserList.setViewportView(jUsers1);

        getContentPane().add(jUserList, new org.netbeans.lib.awtextra.AbsoluteConstraints(631, 44, 209, 530));

        jSend.setBackground(new java.awt.Color(102, 102, 102));
        jSend.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jSend.setForeground(new java.awt.Color(255, 255, 255));
        jSend.setText(">>>");
        jSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSendActionPerformed(evt);
            }
        });
        getContentPane().add(jSend, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 530, -1, 50));
        jSend.getAccessibleContext().setAccessibleName("jSend");

        jTextField1.setEditable(false);
        jTextField1.setBackground(new java.awt.Color(102, 102, 102));
        jTextField1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(255, 255, 255));
        jTextField1.setText("Список Пользователей");
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(631, 16, 209, -1));

        jFile.setBackground(java.awt.SystemColor.controlDkShadow);
        jFile.setFont(jFile.getFont().deriveFont(jFile.getFont().getStyle() & ~java.awt.Font.BOLD, 22));
        jFile.setForeground(new java.awt.Color(255, 255, 255));
        jFile.setText("📎");
        jFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFileActionPerformed(evt);
            }
        });
        getContentPane().add(jFile, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 530, 70, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/123.jpg"))); // NOI18N
        jLabel1.setLabelFor(this);
        jLabel1.setToolTipText("");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-490, 0, 1350, 620));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSendActionPerformed
        // TODO add your handling code here:
        String message = jMessage.getText();
        if (!message.isEmpty()) {
            message = message.replace("\n", "\\n");
            try {
                dos.writeUTF(currentRecipient);
                dos.writeUTF(message);
                dos.writeUTF("---END---");
                dos.flush();
                jMessage.setText("");
            } catch (IOException ex) {
                ex.printStackTrace();
                jChat.append("❌ Ошибка при отправке сообщения\n");
            }
        }
    }//GEN-LAST:event_jSendActionPerformed

    private void sendFile(File file) {
        if (currentRecipient.equals("ALL")) {
            SwingUtilities.invokeLater(() -> jChat.append("⚠️ Нельзя отправлять файлы в общий чат.\n"));
            return;
        }
        if (currentRecipient.equals(username)) {
            SwingUtilities.invokeLater(() -> jChat.append("⚠️ Нельзя отправлять файлы самому себе.\n"));
            return;
        }

        try {
            // Отправка заголовка
            dos.writeUTF("FILE");
            dos.writeUTF(currentRecipient);
            dos.writeUTF(file.getName());
            dos.writeLong(file.length());
            dos.flush();

            // Отправка содержимого файла
            try (FileInputStream fis = new FileInputStream(file)) {
                byte[] buffer = new byte[4096];
                int bytesRead;
                while ((bytesRead = fis.read(buffer)) != -1) {
                    dos.write(buffer, 0, bytesRead);
                }
                dos.flush();
            }

            SwingUtilities.invokeLater(() -> jChat.append("📤 Файл отправлен: " + file.getName() + "\n"));
        } catch (IOException ex) {
            ex.printStackTrace();
            SwingUtilities.invokeLater(() -> jChat.append("❌ Ошибка при отправке файла\n"));
        }
    }

    private void jFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFileActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
        int result = fileChooser.showOpenDialog(this);
        if (result == JFileChooser.APPROVE_OPTION) {
        File file = fileChooser.getSelectedFile();
        sendFile(file);
    }
    }//GEN-LAST:event_jFileActionPerformed

    private void jChatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jChatMouseClicked
        // TODO add your handling code here:
                try {
            int clickedOffset = jChat.viewToModel2D(evt.getPoint());
            int clickedLine = jChat.getLineOfOffset(clickedOffset);

            File file = clickableFiles.get(clickedLine);
            if (file != null && file.exists()) {
                java.awt.Desktop.getDesktop().open(file);
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jChatMouseClicked

    private void jChatMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jChatMouseMoved
        // TODO add your handling code here:
        try {
            int offset = jChat.viewToModel2D(evt.getPoint());
            int line = jChat.getLineOfOffset(offset);

            if (clickableFiles.containsKey(line)) {
                jChat.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
            } else {
                jChat.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
            }
        } catch (Exception e) {
            jChat.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        }
    }//GEN-LAST:event_jChatMouseMoved

    /**
     * @param args the command line arguments
     */
    private String wrapText(String text, int maxLineLength) {
    StringBuilder result = new StringBuilder();
    int lineLength = 0;

    for (String word : text.split(" ")) {
        if (lineLength + word.length() > maxLineLength) {
            result.append("\n");
            lineLength = 0;
        } else if (lineLength > 0) {
            result.append(" ");
            lineLength++;
        }
        result.append(word);
        lineLength += word.length();
    }

    return result.toString();
}
    private void playNotificationSound() {
    try {
        InputStream audioSrc = getClass().getResourceAsStream("/ding.wav");
        if (audioSrc == null) return;

        InputStream bufferedIn = new BufferedInputStream(audioSrc);
        AudioInputStream audioStream = AudioSystem.getAudioInputStream(bufferedIn);
        Clip clip = AudioSystem.getClip();
        clip.open(audioStream);
        clip.start();
    } catch (Exception e) {
        e.printStackTrace();
    }
}


    private void startListening() {
        new Thread(() -> {
            try {
                List<String> userList = new ArrayList<>();
                userList.add("Общий чат");

                while (true) {
                    String line = dis.readUTF();

                    /* ────────────────   И С Т О Р И Я   ──────────────── */
                    if (line.equals("HISTORY")) {
                        List<String> history = new ArrayList<>();
                        while (!(line = dis.readUTF()).equals("---END---")) {
                            history.add(line);
                        }
                        chatHistory.put(currentRecipient, history);

                        SwingUtilities.invokeLater(() -> {
                            jChat.setText("");
                            for (String msg : history) {
                                // ▸ подмена имени на You:
                                String out = msg.contains(username + ":")
                                             ? msg.replaceFirst(Pattern.quote(username) + ":", "You:")
                                             : msg;

                                String wrapped = wrapText(out.replace("\\n", "\n"), 90);
                                jChat.append(wrapped + "\n");
                            }
                        });
                        continue;
                    }

                    /* ────────────────   С П И С О К   ─ П О Л Ь З. ──────────────── */
                    if (line.startsWith("USERLIST")) {
                        userList.clear();
                        userList.add("Общий чат");
                        while (!(line = dis.readUTF()).equals("---END---")) {
                            userList.add(line);
                        }
                        SwingUtilities.invokeLater(() -> {
                            jUsers1.setListData(userList.toArray(new String[0]));
                            jUsers1.setSelectedIndex(0);
                        });
                        continue;
                    }

                    /* ────────────────   Ф А Й Л Ы   ──────────────── */
                    if (line.equals("FILE")) {
                        String sender   = dis.readUTF();
                        String filename = dis.readUTF();
                        long   fileSize = dis.readLong();

                        File downloadsFolder = new File(System.getProperty("user.home"), "Downloads");
                        if (!downloadsFolder.exists()) downloadsFolder.mkdirs();

                        /* авто‑переименование received_Имя(1).ext */
                        String base = filename, ext = "";
                        int dot = filename.lastIndexOf('.');
                        if (dot != -1) { base = filename.substring(0, dot); ext = filename.substring(dot); }

                        File received = new File(downloadsFolder, "received_" + filename);
                        for (int i = 1; received.exists(); i++)
                            received = new File(downloadsFolder, String.format("received_%s(%d)%s", base, i, ext));

                        try (FileOutputStream fos = new FileOutputStream(received)) {
                            byte[] buf = new byte[4096];
                            long left = fileSize;
                            while (left > 0) {
                                int read = dis.read(buf, 0, (int)Math.min(buf.length, left));
                                if (read == -1) throw new IOException("End of stream during file");
                                fos.write(buf, 0, read);
                                left -= read;
                            }
                        }

                        int lineNum = jChat.getLineCount();
                        clickableFiles.put(lineNum, received);

                        File f = received;         // effectively final для лямбды
                        SwingUtilities.invokeLater(() -> {
                            jChat.append("📥 Получен файл от " + sender + ": " + f.getName() +
                                         "\n[🔗] Нажмите, чтобы открыть [🔗]\n");
                            jChat.append("📌 Сохранён в: " + f.getAbsolutePath() + "\n");
                            playNotificationSound();
                        });
                        continue;
                    }

                    /* ────────────────   Т Е К С Т О В Ы Е   ──────────────── */
                    String msg = line;
                    String chatKey;
                    String displayMsg;

                    if (msg.startsWith("PM:")) {
                        String[] parts = msg.split(":", 3);
                        if (parts.length == 3) {
                            String otherUser = parts[1];
                            displayMsg = parts[2];
                            chatKey = otherUser;
                        } else {
                            displayMsg = msg;
                            chatKey = "ALL";
                        }
                    } else {
                        displayMsg = msg;
                        chatKey = "ALL";
                    }

                    /* ▸ подмена имени текущего пользователя на You: */
                    if (displayMsg.contains(username + ":")) {
                        displayMsg = displayMsg.replaceFirst(Pattern.quote(username) + ":", "You:");
                    }

                    /* перенос строк по 90 символов */
                    displayMsg = wrapText(displayMsg.replace("\\n", "\n"), 90);

                    chatHistory.computeIfAbsent(chatKey, k -> new ArrayList<>()).add(displayMsg);

                    if (chatKey.equals(currentRecipient)) {
                        String out = displayMsg;
                        SwingUtilities.invokeLater(() -> {
                            jChat.append(out + "\n");
                            playNotificationSound();
                        });
                    }
                }
            } catch (IOException e) {
                SwingUtilities.invokeLater(() -> jChat.append("❌ Соединение потеряно...\n"));
                e.printStackTrace();
            }

        }).start();
    }




    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea jChat;
    private javax.swing.JButton jFile;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextArea jMessage;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jSend;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JScrollPane jUserList;
    private javax.swing.JList<String> jUsers1;
    // End of variables declaration//GEN-END:variables
}
