/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.clientserver;

import java.io.IOException;
import java.net.Socket;
import java.io.DataInputStream;
import java.io.DataOutputStream;


/**
 *
 * @author btwyu
 */
public class login extends javax.swing.JFrame {

    /**
     * Creates new form mainform
     */
    public login() {
        initComponents();
        setTitle("Tiltedgram | Авторизация"); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jReg = new javax.swing.JButton();
        tlogin = new javax.swing.JTextField();
        jPassword = new javax.swing.JPasswordField();
        jLogin = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jReg.setBackground(new java.awt.Color(153, 153, 153));
        jReg.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jReg.setForeground(new java.awt.Color(255, 255, 255));
        jReg.setText("Регистрация");
        jReg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRegActionPerformed(evt);
            }
        });
        getContentPane().add(jReg, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, 150, 50));

        tlogin.setBackground(new java.awt.Color(153, 153, 153));
        tlogin.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tlogin.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(tlogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 350, 40));

        jPassword.setBackground(new java.awt.Color(153, 153, 153));
        jPassword.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPassword.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, 350, 40));

        jLogin.setBackground(new java.awt.Color(153, 153, 153));
        jLogin.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLogin.setForeground(new java.awt.Color(255, 255, 255));
        jLogin.setText("Вход");
        jLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLoginActionPerformed(evt);
            }
        });
        getContentPane().add(jLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 250, 100, 50));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Логин");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Пароль");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photo_2024-12-10_16-28-24.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, 410));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private boolean isValidInput(String text) {
    return text != null && !text.trim().isEmpty() && text.matches("^[a-zA-Z0-9_.-]{3,}$");
}

    private void jRegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRegActionPerformed
        // TODO add your handling code here:
        String login = tlogin.getText();
        String password = new String(jPassword.getPassword());
        
        if (!isValidInput(login) || !isValidInput(password)) {
        javax.swing.JOptionPane.showMessageDialog(this, "Недопустимые логин или пароль. Разрешены латинские буквы, цифры, '_', '-', '.', минимум 3 символа.");
        return;
        }

        
        try {
            Socket socket = new Socket("localhost", 1234);
            DataOutputStream dos = new DataOutputStream(socket.getOutputStream());
            DataInputStream dis = new DataInputStream(socket.getInputStream());

            dos.writeUTF("REGISTER");
            dos.writeUTF(login);
            dos.writeUTF(password);
            dos.flush();

            String response = dis.readUTF();

            switch (response) {
                case "REGISTERED":
                    javax.swing.JOptionPane.showMessageDialog(this, "Регистрация успешна!");
                    break;
                case "EXISTS":
                    javax.swing.JOptionPane.showMessageDialog(this, "Пользователь уже существует.");
                    break;
                default:
                    javax.swing.JOptionPane.showMessageDialog(this, "Ошибка регистрации.");
            }

            socket.close();
        } catch (IOException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Ошибка подключения к серверу.");
            e.printStackTrace();
        }
    }//GEN-LAST:event_jRegActionPerformed

    private void jLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLoginActionPerformed
    // Получаем логин и пароль из полей ввода
    String login = tlogin.getText();
    String password = new String(jPassword.getPassword());
    
    if (!isValidInput(login) || !isValidInput(password)) {
        javax.swing.JOptionPane.showMessageDialog(this, "Недопустимые логин или пароль. Разрешены латинские буквы, цифры, '_', '-', '.', минимум 3 символа.");
        return;
    }

    try {
        Socket socket = new Socket("localhost", 1234);
        DataOutputStream dos = new DataOutputStream(socket.getOutputStream());
        DataInputStream dis = new DataInputStream(socket.getInputStream());

        dos.writeUTF("LOGIN");
        dos.writeUTF(login);
        dos.writeUTF(password);
        dos.flush();

        String response = dis.readUTF();

        switch (response) {
            case "OK":
                javax.swing.JOptionPane.showMessageDialog(this, "Вход успешен!");
                String username = login;
                new chat(socket, dos, dis, username).setVisible(true);
                this.dispose();
                return;
            case "FAIL":
                javax.swing.JOptionPane.showMessageDialog(this, "Неверный логин или пароль.");
                break;
            default:
                javax.swing.JOptionPane.showMessageDialog(this, "Ошибка при входе.");
                break;
        }

        socket.close();
    } catch (IOException e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Ошибка подключения к серверу.");
        e.printStackTrace();
        }
    }//GEN-LAST:event_jLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton jLogin;
    private javax.swing.JPasswordField jPassword;
    private javax.swing.JButton jReg;
    private javax.swing.JTextField tlogin;
    // End of variables declaration//GEN-END:variables
}
